import 'dotenv/config';
import express, { NextFunction, Request, Response } from 'express';
import cors from 'cors'; import helmet from 'helmet'; import morgan from 'morgan'; import bcrypt from 'bcrypt'; import jwt from 'jsonwebtoken'; import { PrismaClient, DriverStatus, MaintenanceStatus, TripStatus, VehicleStatus } from '@prisma/client';
import { z } from 'zod'; import PDFDocument from 'pdfkit'; import cron from 'node-cron'; import nodemailer from 'nodemailer';

const env = z.object({ DATABASE_URL:z.string().min(1), JWT_SECRET:z.string().min(32), PORT:z.coerce.number().default(4000), CLIENT_URL:z.string().default('http://localhost:5173'), SMTP_HOST:z.string().optional(), SMTP_PORT:z.coerce.number().default(587), SMTP_USER:z.string().optional(), SMTP_PASS:z.string().optional(), SMTP_FROM:z.string().default('TransitOps <noreply@transitops.local>') }).parse(process.env);
const db = new PrismaClient(); const app = express(); app.use(helmet()); app.use(cors({origin:env.CLIENT_URL})); app.use(express.json({limit:'1mb'})); app.use(morgan('tiny'));
type Claims={id:string;role:string}; type Authed=Request & {user?:Claims}; const roles=['Admin','Fleet Manager','Dispatcher','Safety Officer','Financial Analyst'];
const asyncRoute=(fn:(req:Authed,res:Response)=>Promise<unknown>)=>(req:Authed,res:Response,next:NextFunction)=>Promise.resolve(fn(req,res)).catch(next);
const auth=(allowed:string[]=roles)=>(req:Authed,res:Response,next:NextFunction)=>{const token=req.headers.authorization?.replace('Bearer ',''); if(!token)return res.status(401).json({error:'Authentication required'}); try { const u=jwt.verify(token,env.JWT_SECRET) as Claims; if(!allowed.includes(u.role)) return res.status(403).json({error:'Insufficient permission'}); req.user=u; next(); } catch { return res.status(401).json({error:'Invalid or expired token'}); }};
const audit=async(userId:string|undefined,action:string,entity:string,entityId:string,details?:unknown)=>db.auditLog.create({data:{userId,action,entity,entityId,details:details?JSON.stringify(details):null}});
const id=z.object({id:z.string().min(1)}); const vehicleSchema=z.object({registrationNumber:z.string().trim().min(3).max(25),name:z.string().trim().min(2),type:z.string().trim().min(2),region:z.string().trim().min(2),maxLoadKg:z.coerce.number().positive(),odometerKm:z.coerce.number().nonnegative(),acquisitionCost:z.coerce.number().nonnegative(),status:z.nativeEnum(VehicleStatus).optional()});
const driverSchema=z.object({name:z.string().trim().min(2),licenseNumber:z.string().trim().min(3),licenseCategory:z.string().trim().min(1),licenseExpiry:z.coerce.date(),phone:z.string().trim().min(7),safetyScore:z.coerce.number().min(0).max(100).optional(),status:z.nativeEnum(DriverStatus).optional()});
const tripSchema=z.object({source:z.string().trim().min(2),destination:z.string().trim().min(2),region:z.string().trim().min(2),vehicleId:z.string(),driverId:z.string(),cargoWeightKg:z.coerce.number().positive(),plannedDistanceKm:z.coerce.number().positive(),revenue:z.coerce.number().nonnegative().default(0)});
const maintenanceSchema=z.object({vehicleId:z.string(),description:z.string().trim().min(3),cost:z.coerce.number().nonnegative(),status:z.nativeEnum(MaintenanceStatus).optional()});
const fuelSchema=z.object({vehicleId:z.string(),liters:z.coerce.number().positive(),cost:z.coerce.number().nonnegative(),odometerKm:z.coerce.number().nonnegative(),date:z.coerce.date().optional()}); const expenseSchema=z.object({vehicleId:z.string().optional(),category:z.enum(['TOLL','PARKING','INSURANCE','MAINTENANCE','OTHER']),amount:z.coerce.number().positive(),description:z.string().trim().min(2),date:z.coerce.date().optional()});
app.get('/api/health',(_,res)=>res.json({ok:true}));
app.post('/api/auth/login',asyncRoute(async(req,res)=>{const body=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body); const user=await db.user.findFirst({where:{email:body.email,active:true,deletedAt:null},include:{role:true}}); if(!user||!await bcrypt.compare(body.password,user.passwordHash)) return res.status(401).json({error:'Invalid email or password'}); const token=jwt.sign({id:user.id,role:user.role.name},env.JWT_SECRET,{expiresIn:'8h'}); res.json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role.name}}); }));
app.get('/api/auth/me',auth(),asyncRoute(async(req,res)=>res.json(await db.user.findUnique({where:{id:req.user!.id},include:{role:true}}))));
function crud(path:string, model:'vehicle'|'driver', schema:z.AnyZodObject, allowed:string[]){ const delegate=(db as any)[model]; app.get(path,auth(allowed),asyncRoute(async(req,res)=>{const q=String(req.query.q||''); const where={deletedAt:null,...(q?model==='vehicle'?{OR:[{name:{contains:q}},{registrationNumber:{contains:q}}]}:{OR:[{name:{contains:q}},{licenseNumber:{contains:q}}]}:{})}; res.json(await delegate.findMany({where,orderBy:{createdAt:'desc'}}));})); app.post(path,auth(allowed),asyncRoute(async(req,res)=>{const data=schema.parse(req.body); const row=await delegate.create({data}); await audit(req.user?.id,'CREATE',model,row.id,data); res.status(201).json(row);})); app.patch(path+'/:id',auth(allowed),asyncRoute(async(req,res)=>{const data=schema.partial().parse(req.body); const row=await delegate.update({where:id.parse(req.params),data}); await audit(req.user?.id,'UPDATE',model,row.id,data); res.json(row);})); app.delete(path+'/:id',auth(allowed),asyncRoute(async(req,res)=>{const row=await delegate.update({where:id.parse(req.params),data:{deletedAt:new Date()}}); await audit(req.user?.id,'DELETE',model,row.id); res.status(204).end();})); }
crud('/api/vehicles','vehicle',vehicleSchema,['Admin','Fleet Manager']); crud('/api/drivers','driver',driverSchema,['Admin','Safety Officer','Dispatcher']);
app.get('/api/dispatch-options',auth(['Admin','Dispatcher']),asyncRoute(async(_,res)=>{const now=new Date(); const [vehicles,drivers]=await Promise.all([db.vehicle.findMany({where:{status:'AVAILABLE',deletedAt:null}}),db.driver.findMany({where:{status:'AVAILABLE',licenseExpiry:{gt:now},deletedAt:null}})]);res.json({vehicles,drivers});}));
app.get('/api/trips',auth(),asyncRoute(async(_,res)=>res.json(await db.trip.findMany({where:{deletedAt:null},include:{vehicle:true,driver:true},orderBy:{createdAt:'desc'}}))));
app.post('/api/trips',auth(['Admin','Dispatcher']),asyncRoute(async(req,res)=>{const d=tripSchema.parse(req.body); const [v,driver]=await Promise.all([db.vehicle.findUnique({where:{id:d.vehicleId}}),db.driver.findUnique({where:{id:d.driverId}})]); if(!v||!driver) return res.status(404).json({error:'Vehicle or driver not found'}); if(v.status!==VehicleStatus.AVAILABLE) return res.status(409).json({error:'Vehicle is not available for dispatch'}); if(driver.status!==DriverStatus.AVAILABLE||driver.licenseExpiry<=new Date()) return res.status(409).json({error:'Driver is suspended, unavailable, or license has expired'}); if(d.cargoWeightKg>v.maxLoadKg)return res.status(422).json({error:'Cargo weight exceeds vehicle capacity'}); const trip=await db.trip.create({data:{...d,reference:`TRP-${Date.now()}`},include:{vehicle:true,driver:true}}); await audit(req.user?.id,'CREATE','trip',trip.id,d);res.status(201).json(trip);}));
app.post('/api/trips/:id/:action',auth(['Admin','Dispatcher']),asyncRoute(async(req,res)=>{const action=z.enum(['dispatch','complete','cancel']).parse(req.params.action);const trip=await db.trip.findUnique({where:id.parse(req.params)});if(!trip)return res.status(404).json({error:'Trip not found'}); if(action==='dispatch'){if(trip.status!==TripStatus.DRAFT)return res.status(409).json({error:'Only draft trips can be dispatched'}); await db.$transaction([db.trip.update({where:{id:trip.id},data:{status:'DISPATCHED',dispatchedAt:new Date()}}),db.vehicle.updateMany({where:{id:trip.vehicleId,status:'AVAILABLE'},data:{status:'ON_TRIP'}}),db.driver.updateMany({where:{id:trip.driverId,status:'AVAILABLE',licenseExpiry:{gt:new Date()}},data:{status:'ON_TRIP'}})]); const fresh=await db.trip.findUnique({where:{id:trip.id}}); if(!fresh||fresh.status!=='DISPATCHED')return res.status(409).json({error:'Vehicle or driver became unavailable'});} else {if(trip.status!=='DISPATCHED')return res.status(409).json({error:'Only dispatched trips can be completed or cancelled'}); await db.$transaction([db.trip.update({where:{id:trip.id},data:{status:action==='complete'?'COMPLETED':'CANCELLED',completedAt:action==='complete'?new Date():null}}),db.vehicle.update({where:{id:trip.vehicleId},data:{status:'AVAILABLE'}}),db.driver.update({where:{id:trip.driverId},data:{status:'AVAILABLE'}})]);} await audit(req.user?.id,action.toUpperCase(),'trip',trip.id);res.json(await db.trip.findUnique({where:{id:trip.id},include:{vehicle:true,driver:true}}));}));
app.get('/api/maintenance',auth(['Admin','Fleet Manager']),asyncRoute(async(_,res)=>res.json(await db.maintenanceLog.findMany({include:{vehicle:true},orderBy:{openedAt:'desc'}}))));
app.post('/api/maintenance',auth(['Admin','Fleet Manager']),asyncRoute(async(req,res)=>{const d=maintenanceSchema.parse(req.body);const v=await db.vehicle.findUnique({where:{id:d.vehicleId}});if(!v||v.status==='RETIRED')return res.status(409).json({error:'Vehicle cannot enter maintenance'});const row=await db.$transaction(async tx=>{await tx.vehicle.update({where:{id:d.vehicleId},data:{status:'IN_SHOP'}});return tx.maintenanceLog.create({data:d,include:{vehicle:true}})});res.status(201).json(row);}));
app.post('/api/maintenance/:id/close',auth(['Admin','Fleet Manager']),asyncRoute(async(req,res)=>{const log=await db.maintenanceLog.findUnique({where:id.parse(req.params)});if(!log)return res.status(404).json({error:'Maintenance record not found'});const row=await db.$transaction(async tx=>{const m=await tx.maintenanceLog.update({where:{id:log.id},data:{status:'CLOSED',closedAt:new Date()}});await tx.vehicle.updateMany({where:{id:log.vehicleId,status:{not:'RETIRED'}},data:{status:'AVAILABLE'}});return m});res.json(row);}));
function simple(path:string, model:'fuelLog'|'expense', schema:z.ZodTypeAny, allowed:string[]){const d=(db as any)[model];app.get(path,auth(allowed),asyncRoute(async(_,res)=>res.json(await d.findMany({include:{vehicle:true},orderBy:{date:'desc'}}))));app.post(path,auth(allowed),asyncRoute(async(req,res)=>res.status(201).json(await d.create({data:schema.parse(req.body)}))));}
simple('/api/fuel-logs','fuelLog',fuelSchema,['Admin','Fleet Manager','Financial Analyst']);simple('/api/expenses','expense',expenseSchema,['Admin','Financial Analyst']);
app.get('/api/analytics',auth(),asyncRoute(async(_,res)=>{const [vehicles,trips,drivers,fuel,maintenance,expenses]=await Promise.all([db.vehicle.findMany({where:{deletedAt:null}}),db.trip.findMany({where:{deletedAt:null}}),db.driver.findMany({where:{deletedAt:null}}),db.fuelLog.findMany(),db.maintenanceLog.findMany(),db.expense.findMany()]);const total=vehicles.length||1, completed=trips.filter(t=>t.status==='COMPLETED'), fuelCost=fuel.reduce((s,x)=>s+x.cost,0),maintCost=maintenance.reduce((s,x)=>s+x.cost,0),expenseCost=expenses.reduce((s,x)=>s+x.amount,0);const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i);return {month:d.toLocaleString('en',{month:'short'}),fuel:0,cost:0}});fuel.forEach(f=>{const m=months.find(x=>x.month===f.date.toLocaleString('en',{month:'short'}));if(m){m.fuel+=f.liters;m.cost+=f.cost}});res.json({kpis:{activeVehicles:vehicles.filter(x=>x.status!=='RETIRED').length,availableVehicles:vehicles.filter(x=>x.status==='AVAILABLE').length,inMaintenance:vehicles.filter(x=>x.status==='IN_SHOP').length,activeTrips:trips.filter(x=>x.status==='DISPATCHED').length,pendingTrips:trips.filter(x=>x.status==='DRAFT').length,driversOnDuty:drivers.filter(x=>x.status==='ON_TRIP').length,utilization:+(vehicles.filter(x=>x.status==='ON_TRIP').length/total*100).toFixed(1),operationalCost:fuelCost+maintCost+expenseCost,fuelEfficiency:+(completed.reduce((s,x)=>s+(x.actualDistanceKm||x.plannedDistanceKm),0)/(fuel.reduce((s,x)=>s+x.liters,0)||1)).toFixed(2)},monthly:months,topVehicles:vehicles.map(v=>({name:v.name,cost:fuel.filter(f=>f.vehicleId===v.id).reduce((s,x)=>s+x.cost,0)+maintenance.filter(m=>m.vehicleId===v.id).reduce((s,x)=>s+x.cost,0),roi:+((completed.filter(t=>t.vehicleId===v.id).reduce((s,t)=>s+t.revenue,0)-fuel.filter(f=>f.vehicleId===v.id).reduce((s,x)=>s+x.cost,0)-maintenance.filter(m=>m.vehicleId===v.id).reduce((s,x)=>s+x.cost,0))/(v.acquisitionCost||1)).toFixed(2)})).sort((a,b)=>b.cost-a.cost),driverSafety:drivers.map(d=>({name:d.name,score:d.safetyScore}))});}));
app.get('/api/reports/export/:format',auth(['Admin','Financial Analyst']),asyncRoute(async(req,res)=>{const format=z.enum(['csv','pdf']).parse(req.params.format);const rows=await db.expense.findMany({include:{vehicle:true},orderBy:{date:'desc'}});if(format==='csv'){res.type('text/csv').attachment('transitops-expenses.csv').send(['Date,Vehicle,Category,Description,Amount',...rows.map(r=>`${r.date.toISOString().slice(0,10)},${r.vehicle?.registrationNumber||''},${r.category},"${r.description.replaceAll('"','""')}",${r.amount}`)].join('\n'));return;}res.type('application/pdf').attachment('transitops-expenses.pdf');const doc=new PDFDocument({margin:45});doc.pipe(res);doc.fontSize(20).text('TransitOps Expense Report');doc.moveDown().fontSize(10);rows.forEach(r=>doc.text(`${r.date.toISOString().slice(0,10)}  |  ${r.category}  |  ${r.vehicle?.registrationNumber||'General'}  |  ₹${r.amount.toFixed(2)}  |  ${r.description}`));doc.end();}));
app.get('/api/users',auth(['Admin']),asyncRoute(async(_,res)=>res.json(await db.user.findMany({where:{deletedAt:null},select:{id:true,name:true,email:true,active:true,role:true,createdAt:true}}))));
app.post('/api/users',auth(['Admin']),asyncRoute(async(req,res)=>{const d=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),role:z.enum(roles as [string,...string[]])}).parse(req.body);const role=await db.role.findUniqueOrThrow({where:{name:d.role}});res.status(201).json(await db.user.create({data:{name:d.name,email:d.email,passwordHash:await bcrypt.hash(d.password,12),roleId:role.id}}));}));
cron.schedule('0 8 * * *',async()=>{const until=new Date();until.setDate(until.getDate()+30);const drivers=await db.driver.findMany({where:{licenseExpiry:{gte:new Date(),lte:until},deletedAt:null}});if(!env.SMTP_HOST)return;const t=nodemailer.createTransport({host:env.SMTP_HOST,port:env.SMTP_PORT,auth:env.SMTP_USER?{user:env.SMTP_USER,pass:env.SMTP_PASS}:undefined});for(const d of drivers){await t.sendMail({from:env.SMTP_FROM,to:env.SMTP_USER!,subject:'TransitOps license reminder',text:`${d.name}'s license expires on ${d.licenseExpiry.toDateString()}.`});await audit(undefined,'LICENSE_REMINDER','driver',d.id);}});
app.use((err:unknown,_req:Request,res:Response,_next:NextFunction)=>{if(err instanceof z.ZodError)return res.status(422).json({error:'Validation failed',issues:err.flatten()});if((err as any)?.code==='P2002')return res.status(409).json({error:'A record with that unique value already exists'});console.error(err);return res.status(500).json({error:'Unexpected server error'});});app.listen(env.PORT,()=>console.log(`TransitOps API listening on ${env.PORT}`));
